In [ ]:
!pip3 install fastai

In [ ]:
from fastai.vision.all import *

In [ ]:
path = untar_data(URLs.PETS)/'grizzly'

In [ ]:
path

AttributeError: ignored

In [ ]:
dest = 'images/grizzly.jpg'
#download_url(ims[0], dest)

In [ ]:
dest

'images/grizzly.jpg'

In [ ]:
results = search_images_bing(key, 'grizzly bear')
ims = results.attrgot('content_url')
len(ims)

In [ ]:
import torch

In [ ]:
torch.Tensor(4,4)

tensor([[3.1025e-35, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [ ]:
torch.rand(2, 3) # случайное равномерное распределение

tensor([[0.3835, 0.9707, 0.5268],
        [0.1730, 0.4657, 0.6388]])

In [ ]:
torch.randn(2, 3) # случайное нормальное распределение

tensor([[ 0.2569,  0.1955,  1.0948],
        [-1.1033, -0.8579,  0.9320]])

In [ ]:
torch.ones(2, 3).fill_(34) # заполнение матрицы одинаковыми значениями

tensor([[34., 34., 34.],
        [34., 34., 34.]])

In [ ]:
npy = np.random.rand(2, 3)
npy

array([[0.71774612, 0.19178166, 0.21630851],
       [0.44229226, 0.53134391, 0.42079998]])

In [ ]:
torch.from_numpy(npy) # создаем тензоры из массива NumPy

tensor([[0.7177, 0.1918, 0.2163],
        [0.4423, 0.5313, 0.4208]], dtype=torch.float64)

# **Типы и размеры тензора**

In [ ]:
import torch
import numpy as np

In [ ]:
npy = np.random.rand(2, 3)

In [ ]:
npy

array([[0.54640094, 0.49249895, 0.852286  ],
       [0.94964371, 0.52611408, 0.58661298]])

In [ ]:
torch.from_numpy(npy) # перевод из numpy в torch

tensor([[0.5464, 0.4925, 0.8523],
        [0.9496, 0.5261, 0.5866]], dtype=torch.float64)

In [ ]:
x = torch.FloatTensor([[1, 2, 3],
                      [4, 5, 6]])
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
x.long() # перевод в int

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x = torch.tensor([[1, 2, 3],
                  [4, 5, 6]], dtype=torch.int64)
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x = x.float()
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
torch.add(x, x) # умножение тензора самого на себя

tensor([[ 2.,  4.,  6.],
        [ 8., 10., 12.]])

In [ ]:
torch.arange(6)

tensor([0, 1, 2, 3, 4, 5])

In [ ]:
x.view(2, 3)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
torch.sum(x, dim=0).int() # сумма столбцов

tensor([5, 7, 9], dtype=torch.int32)

In [ ]:
torch.arange(6)

tensor([0, 1, 2, 3, 4, 5])

In [ ]:
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
x.view(2, 3)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
torch.sum(x, dim=1)

tensor([ 6., 15.])

In [ ]:
torch.transpose(x,0,1)

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

# **Обращение по индексу, срезы и объединение**

In [ ]:
x = torch.arange(6).view(2, 3)

In [ ]:
x[:1, :2]

tensor([[0, 1]])

In [ ]:
x

tensor([[0, 1, 2],
        [3, 4, 5]])

**Сложный доступ по индексам:**

In [ ]:
indices = torch.LongTensor([0, 2])

In [ ]:
x

tensor([[0, 1, 2],
        [3, 4, 5]])

In [ ]:
torch.index_select(x, dim=1, index=indices) #!!!!!!!!!!!!!!!!!!

tensor([[0, 2],
        [3, 5]])

_____________________________________

In [ ]:
indices = torch.LongTensor([0, 0])

In [ ]:
torch.index_select(x, dim=0, index=indices)

tensor([[0, 1, 2],
        [0, 1, 2]])

_____________________________

Задаем 2 группы координат чисел и из матрицы выбираются эти числа создавая 1 мерный тензор

In [ ]:
row_indices = torch.arange(2).long()
row_indices

tensor([0, 1])

In [ ]:
col_indices = torch.LongTensor([0, 1])
col_indices

tensor([0, 1])

In [ ]:
x

tensor([[0, 1, 2],
        [3, 4, 5]])

In [ ]:
x[row_indices, col_indices]

tensor([0, 4])

____________________________

**Контагенация**

In [ ]:
x = torch.arange(6).view(2,3)
x

tensor([[0, 1, 2],
        [3, 4, 5]])

In [ ]:
torch.cat([x, x], dim=0)

tensor([[0, 1, 2],
        [3, 4, 5],
        [0, 1, 2],
        [3, 4, 5]])

In [ ]:
torch.cat([x, x], dim=1)

tensor([[0, 1, 2, 0, 1, 2],
        [3, 4, 5, 3, 4, 5]])

In [ ]:
y = torch.stack([x, x])

In [ ]:
x1 = torch.arange(6).view(2, 3)
x1

tensor([[0, 1, 2],
        [3, 4, 5]])

In [ ]:
x2 = torch.ones(3, 2)
x2

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [ ]:
x2[:, 1]

tensor([1., 1., 1.])

In [ ]:
x2[:, 1] += 1 #  прибавляем к столбцу число

In [ ]:
x1

tensor([[0, 1, 2],
        [3, 4, 5]])

In [ ]:
describe(torch.mm(x1, x2))

# **Проверка. Первая глава**

In [ ]:
import torch

**1. Создайте двумерный тензор, после чего добавьте в него новое измерение размером 1 перед измерением 0.**

In [ ]:
a = torch.rand(3,3)
a

tensor([[0.2434, 0.4706, 0.6867],
        [0.9855, 0.9357, 0.8029],
        [0.0630, 0.9719, 0.9990]])

In [ ]:
a = a.unsqueeze(0) # добавляет новое измерение

In [ ]:
a

tensor([[[0.2434, 0.4706, 0.6867],
         [0.9855, 0.9357, 0.8029],
         [0.0630, 0.9719, 0.9990]]])

**2. Удалите дополнительное измерение, которое вы только что добавили в предыдущий тензор.**

In [ ]:
a.squeeze(0)

tensor([[0.2434, 0.4706, 0.6867],
        [0.9855, 0.9357, 0.8029],
        [0.0630, 0.9719, 0.9990]])

**3. Создайте случайный тензор формой 5 × 3 в интервале [3, 7).**

In [ ]:
3 + torch.rand(5,3)*(7-3)

tensor([[5.0193, 5.9209, 6.0803],
        [3.5559, 5.5533, 3.1975],
        [6.9156, 5.5567, 3.9628],
        [6.7137, 6.3318, 3.8497],
        [4.0258, 6.2586, 6.3773]])

**4. Создайте тензор со значениями, взятыми из нормального распределения (математическое ожидание = 0, стандартное отклонение = 1).**

In [ ]:
a = torch.rand(3,3)
a.normal_()

tensor([[ 0.2906,  1.2943,  0.0738],
        [ 0.7053, -0.1759,  0.9373],
        [-1.0881, -0.1298,  0.9830]])

**5. Извлеките индексы всех ненулевых элементов из тензора torch.Tensor([1, 1, 1, 0, 1]).**

In [ ]:
a = torch.Tensor([1, 1, 1, 0, 1])

In [ ]:
torch.nonzero(a)

tensor([[0],
        [1],
        [2],
        [4]])

**6. Создайте случайный тензор размером (3,1), а затем горизонтально разместите в ряд четыре его копии.**

In [ ]:
a = torch.rand(3,1)
a

tensor([[0.0112],
        [0.2256],
        [0.3104]])

In [ ]:
a.expand(3,4)

tensor([[0.0112, 0.0112, 0.0112, 0.0112],
        [0.2256, 0.2256, 0.2256, 0.2256],
        [0.3104, 0.3104, 0.3104, 0.3104]])

**7. Верните пакетное произведение двух трехмерных матриц (a=torch.rand(3,4,5), b=torch.rand(3,5,4)).**

In [ ]:
a=torch.rand(3,4,5)
a

tensor([[[0.0101, 0.8154, 0.5314, 0.6388, 0.1552],
         [0.3173, 0.8920, 0.0328, 0.5002, 0.8187],
         [0.2578, 0.8911, 0.6409, 0.1597, 0.0215],
         [0.9825, 0.4277, 0.0819, 0.3686, 0.6359]],

        [[0.6950, 0.0471, 0.3349, 0.3760, 0.6559],
         [0.4083, 0.0081, 0.5169, 0.3561, 0.1334],
         [0.8996, 0.4122, 0.0299, 0.2961, 0.1153],
         [0.7518, 0.7955, 0.5410, 0.2421, 0.7969]],

        [[0.2597, 0.0130, 0.7634, 0.8982, 0.3489],
         [0.3929, 0.5344, 0.3267, 0.2250, 0.6849],
         [0.1652, 0.4608, 0.7056, 0.4511, 0.4787],
         [0.9802, 0.6807, 0.1673, 0.9048, 0.1962]]])

In [ ]:
b=torch.rand(3,5,4)
b

tensor([[[0.2879, 0.5829, 0.9801, 0.7400],
         [0.5566, 0.4217, 0.6443, 0.6633],
         [0.3541, 0.1272, 0.9072, 0.4997],
         [0.3720, 0.0536, 0.8031, 0.0452],
         [0.3737, 0.6548, 0.2590, 0.3403]],

        [[0.1076, 0.7862, 0.5828, 0.4523],
         [0.3108, 0.0724, 0.1252, 0.3926],
         [0.3673, 0.8341, 0.2727, 0.5814],
         [0.9778, 0.2167, 0.5062, 0.7940],
         [0.6372, 0.8068, 0.4345, 0.0043]],

        [[0.0349, 0.9382, 0.6337, 0.6027],
         [0.0571, 0.6894, 0.0401, 0.6581],
         [0.2659, 0.5399, 0.1492, 0.9057],
         [0.3982, 0.2259, 0.7580, 0.4519],
         [0.3509, 0.4869, 0.5853, 0.5593]]])

In [ ]:
torch.bmm(a,b)

tensor([[[0.9405, 0.5532, 1.5705, 0.8956],
         [1.0914, 1.1282, 1.5292, 1.1441],
         [0.8645, 0.6302, 1.5420, 1.1167],
         [0.9247, 1.1996, 1.7736, 1.2848]],

        [[0.9980, 1.4398, 0.9775, 0.8289],
         [0.6695, 0.9375, 0.6181, 0.7717],
         [0.5990, 0.9193, 0.7840, 0.8217],
         [1.2714, 1.7953, 1.1540, 1.1625]],

        [[0.6929, 1.0375, 1.1641, 1.4575],
         [0.4610, 1.2976, 0.8906, 1.3691],
         [0.5673, 1.1885, 0.8506, 1.5135],
         [0.5467, 1.7790, 1.4741, 1.7089]]])

**8. Верните пакетное произведение трехмерной и двумерной матриц (a=torch.rand(3,4,5), b=torch.rand(5,4)).**

In [ ]:
a = torch.rand(3, 4, 5)
a

In [ ]:
b = torch.rand(5, 4)
b

In [ ]:
b.unsqueeze(0)

In [ ]:
a.size(0)

3

In [ ]:
b.size()

torch.Size([5, 4])

In [ ]:
torch.bmm(a, b.unsqueeze(0).expand(a.size(0), *b.size()))

tensor([[[0.7381, 0.7605, 0.5121, 1.0784],
         [0.5935, 0.5316, 0.6459, 0.8957],
         [0.8106, 0.8121, 0.8602, 1.3159],
         [1.0408, 1.4373, 1.3706, 1.9253]],

        [[0.8156, 0.6973, 0.5550, 0.9750],
         [0.7147, 0.8549, 0.9439, 1.3538],
         [0.6956, 1.0095, 0.5616, 1.1597],
         [0.5493, 0.7389, 0.7119, 0.9568]],

        [[1.5043, 1.8066, 1.6368, 2.5471],
         [1.0253, 1.5892, 1.2344, 1.7319],
         [1.1151, 1.0120, 1.1551, 1.8361],
         [0.8770, 1.0279, 1.1539, 1.5575]]])

# **CUDA**

In [ ]:
import torch
print (torch.cuda.is_available())

False
