In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
import os
import sys, random, math
from collections import Counter
import numpy as np

In [ ]:
np.random.seed(1)
random.seed(1)

In [ ]:
f = open('/content/gdrive/MyDrive/Colab Notebooks/DOM/Grokaem/reviews.txt')
raw_reviews = f.readlines()
f.close()

In [ ]:
raw_reviews = raw_reviews[:25000]

In [ ]:
len(raw_reviews)

25000

In [ ]:
raw_reviews # список строк - отзывов

In [ ]:
raw_reviews[0]

In [ ]:
# список списков в которых каждое слово - отдельный элемент через включая пробелы и тире
# типа: [['rff','we3'],['jkh','ooiu']]
tokens = list(map(lambda x:(x.split(" ")), raw_reviews))

In [ ]:
tokens

In [ ]:
wordcnt = Counter() # выдает словарь в котором ключ - это слово в переданном списке,
                    # а значение - это сколько раз данное слова появляется в списке
for sent in tokens:
  for word in sent:
    wordcnt[word] -= 1
# в данном случае передается словарь и подсчет ведется для всех слов ваще (почему-то в обратную сторону)

In [ ]:
wordcnt['insane']

-225

**most_common([n]) - возвращает n наиболее часто встречающихся элементов, в порядке убывания встречаемости. Если n не указано, возвращаются все элементы.**

**>>> Counter('abracadabra').most_common(3)**

**[('a', 5), ('r', 2), ('b', 2)]**

In [ ]:
wordcnt.most_common()

[('chantings', -1),
 ('houselessness', -1),
 ('jetliner', -1),
 ('pataki', -1),
 ('bermuda', -1),
 ('suffocate', -1),
 ('loooonnnnng', -1),
 ('fume', -1),
 ('halitosis', -1),
 ('excoriated', -1),
 ('unexpectedness', -1),
 ('sontag', -1),
 ('intoned', -1),
 ('dispersion', -1),
 ('godby', -1),
 ('maupins', -1),
 ('decrescendos', -1),
 ('humidity', -1),
 ('bleibtreau', -1),
 ('ufortunately', -1),
 ('pyschosis', -1),
 ('listner', -1),
 ('overexciting', -1),
 ('acquaints', -1),
 ('stetner', -1),
 ('taupin', -1),
 ('rodding', -1),
 ('spotless', -1),
 ('necking', -1),
 ('alongno', -1),
 ('sutdying', -1),
 ('alterior', -1),
 ('hmmmmmmmm', -1),
 ('jbj', -1),
 ('sidey', -1),
 ('khiladi', -1),
 ('phawa', -1),
 ('yashpal', -1),
 ('jadoo', -1),
 ('turnout', -1),
 ('jodha', -1),
 ('jetski', -1),
 ('bahiyyaji', -1),
 ('hemlines', -1),
 ('plonking', -1),
 ('kumr', -1),
 ('crorepati', -1),
 ('kareen', -1),
 ('amu', -1),
 ('sensharma', -1),
 ('mente', -1),
 ('asesino', -1),
 ('milimeters', -1),
 ('vicev

In [ ]:
# короче здесь получается список слов от наиболее часто встречающихся к менее часто
vocab = list(set(map(lambda x:x[0], wordcnt.most_common())))

In [ ]:
vocab

['',
 'amontillado',
 'astronomers',
 'pantoliano',
 'reliefus',
 'delattre',
 'urich',
 'hamlet',
 'bakelite',
 'filmcow',
 'transatlantic',
 'beds',
 'mama',
 'womanize',
 'goosebump',
 'migr',
 'scatter',
 'flicker',
 'appetites',
 'patriots',
 'miscegenation',
 'afterall',
 'minneli',
 'foulmouthed',
 'chess',
 'starling',
 'nathalie',
 'akshay',
 'mach',
 'muzzled',
 'aquarium',
 'morty',
 'child',
 'worried',
 'spicing',
 'potch',
 'traumas',
 'lifelike',
 'fry',
 'kanye',
 'nelli',
 'lessor',
 'embracing',
 'tie',
 'blanding',
 'expounds',
 'skeptiscism',
 'pixies',
 'canada',
 'swern',
 'munchausen',
 'sodeberg',
 'staple',
 'fabric',
 'skerrit',
 'wuthering',
 'rawks',
 'sintown',
 'necronomicon',
 'basket',
 'kerouac',
 'stage',
 'hypothesis',
 'radames',
 'definition',
 'manager',
 'shuttered',
 'scumbags',
 'baaaaaad',
 'malleable',
 'brien',
 'innes',
 'tumor',
 'lonnrot',
 'dissed',
 'blueberry',
 'crescendoing',
 'dunstan',
 'unknown',
 'partied',
 'suffocated',
 'muggin

In [ ]:
# создает словарь: ключ - наиболее встречающееся слово,
                # значение - порядковый номер
word2index = {}
for i,word in enumerate(vocab):
  word2index[word]=i

In [ ]:
word2index

{'': 0,
 'amontillado': 1,
 'astronomers': 2,
 'pantoliano': 3,
 'reliefus': 4,
 'delattre': 5,
 'urich': 6,
 'hamlet': 7,
 'bakelite': 8,
 'filmcow': 9,
 'transatlantic': 10,
 'beds': 11,
 'mama': 12,
 'womanize': 13,
 'goosebump': 14,
 'migr': 15,
 'scatter': 16,
 'flicker': 17,
 'appetites': 18,
 'patriots': 19,
 'miscegenation': 20,
 'afterall': 21,
 'minneli': 22,
 'foulmouthed': 23,
 'chess': 24,
 'starling': 25,
 'nathalie': 26,
 'akshay': 27,
 'mach': 28,
 'muzzled': 29,
 'aquarium': 30,
 'morty': 31,
 'child': 32,
 'worried': 33,
 'spicing': 34,
 'potch': 35,
 'traumas': 36,
 'lifelike': 37,
 'fry': 38,
 'kanye': 39,
 'nelli': 40,
 'lessor': 41,
 'embracing': 42,
 'tie': 43,
 'blanding': 44,
 'expounds': 45,
 'skeptiscism': 46,
 'pixies': 47,
 'canada': 48,
 'swern': 49,
 'munchausen': 50,
 'sodeberg': 51,
 'staple': 52,
 'fabric': 53,
 'skerrit': 54,
 'wuthering': 55,
 'rawks': 56,
 'sintown': 57,
 'necronomicon': 58,
 'basket': 59,
 'kerouac': 60,
 'stage': 61,
 'hypothesis'

In [ ]:
# здесь создается список списков, где каждый список - это комментарий, здесь каждое слово переведено в цифру
# т.е все комментарии состоят из цифр, каждое слово в любом комментарии имеет свою цифру
concatenated = list()
input_dataset = list()
for sent in tokens:
  sent_indices = list()
  for word in sent:
    try:
      sent_indices.append(word2index[word])
      concatenated.append(word2index[word])
    except:
      ""
  input_dataset.append(sent_indices)
concatenated = np.array(concatenated)

In [ ]:
concatenated # получили список кодов слов, чем меньше число, тем чаще встречается слово

array([ 8142, 27520, 65986, ..., 21065,     0, 40756])

In [ ]:
input_dataset

# **Данные подготовлены!!! input_dataset**

**Они выглядят: [[333,2872,34,1],[34,714,343],...,[32345,6687]]**

_______________________________________________

In [ ]:
random.shuffle(input_dataset)
alpha, iterations = (0.05, 2)
hidden_size,window,negative = (50,2,5)

In [ ]:
weights_0_1 = (np.random.rand(len(vocab),hidden_size) - 0.5) * 0.2
weights_0_1.shape

(67782, 50)

In [ ]:
weights_0_1

array([[-0.0165956 ,  0.0440649 , -0.09997713, ..., -0.04127717,
        -0.04244493, -0.07399429],
       [-0.09612661,  0.03576711, -0.05767438, ...,  0.0147359 ,
        -0.09942593,  0.02342898],
       [-0.03467102,  0.00541162,  0.07718842, ...,  0.0425978 ,
         0.0119434 , -0.0974888 ],
       ...,
       [ 0.00845357,  0.06279174, -0.02753424, ..., -0.04708552,
         0.09088481, -0.09060925],
       [-0.0918184 , -0.05563701, -0.07440146, ..., -0.03654988,
         0.02375404,  0.0986769 ],
       [ 0.00420763,  0.08744966,  0.06572655, ..., -0.04477787,
        -0.00512322,  0.07485452]])

In [ ]:
weights_1_2 = np.random.rand(len(vocab),hidden_size)*0
weights_1_2

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
weights_1_2.shape

(67782, 50)

In [ ]:
layer_2_target = np.zeros(negative+1)
layer_2_target[0] = 1

In [ ]:
layer_2_target

array([1., 0., 0., 0., 0., 0.])

In [ ]:
word2index.items()

dict_items([('', 0), ('amontillado', 1), ('astronomers', 2), ('pantoliano', 3), ('reliefus', 4), ('delattre', 5), ('urich', 6), ('hamlet', 7), ('bakelite', 8), ('filmcow', 9), ('transatlantic', 10), ('beds', 11), ('mama', 12), ('womanize', 13), ('goosebump', 14), ('migr', 15), ('scatter', 16), ('flicker', 17), ('appetites', 18), ('patriots', 19), ('miscegenation', 20), ('afterall', 21), ('minneli', 22), ('foulmouthed', 23), ('chess', 24), ('starling', 25), ('nathalie', 26), ('akshay', 27), ('mach', 28), ('muzzled', 29), ('aquarium', 30), ('morty', 31), ('child', 32), ('worried', 33), ('spicing', 34), ('potch', 35), ('traumas', 36), ('lifelike', 37), ('fry', 38), ('kanye', 39), ('nelli', 40), ('lessor', 41), ('embracing', 42), ('tie', 43), ('blanding', 44), ('expounds', 45), ('skeptiscism', 46), ('pixies', 47), ('canada', 48), ('swern', 49), ('munchausen', 50), ('sodeberg', 51), ('staple', 52), ('fabric', 53), ('skerrit', 54), ('wuthering', 55), ('rawks', 56), ('sintown', 57), ('necrono

In [ ]:
word2index['beautiful']

47682

In [ ]:
weights_0_1.shape

(67782, 50)

In [ ]:
weights_0_1[:2] # т.е. weights_0_1[index] - это вектор 1х50

array([[-0.0165956 ,  0.0440649 , -0.09997713, -0.03953349, -0.07064882,
        -0.08153228, -0.06274796, -0.03088785, -0.02064651,  0.00776335,
        -0.0161611 ,  0.0370439 , -0.05910955,  0.07562349, -0.09452248,
         0.0340935 , -0.01653904,  0.01173797, -0.07192261, -0.0603797 ,
         0.06014891,  0.09365232, -0.03731516,  0.03846452,  0.07527783,
         0.07892133, -0.08299116, -0.09218904, -0.06603392,  0.0756285 ,
        -0.08033063, -0.01577847,  0.09157791,  0.00663306,  0.03837542,
        -0.03689687,  0.03730019,  0.06692513, -0.09634234,  0.05002886,
         0.09777222,  0.04963313, -0.0439112 ,  0.05785587, -0.0793548 ,
        -0.01042129,  0.0817191 , -0.04127717, -0.04244493, -0.07399429],
       [-0.09612661,  0.03576711, -0.05767438, -0.04689067, -0.00168537,
        -0.08932749,  0.01482352, -0.07065429,  0.01786111,  0.03995167,
        -0.07953311, -0.0171888 ,  0.03888003, -0.01716415, -0.09000931,
         0.00717928,  0.03275893,  0.00297782,  0.

In [ ]:
def similar(target='beautiful'):
  target_index = word2index[target] # здесь заложена цифра слова 'beautiful' = 2023

  scores = Counter()
  for word,index in word2index.items():
    raw_difference = weights_0_1[index] - (weights_0_1[target_index]) # т.е. ((вектор 1х100) - 2023)
    squared_difference = raw_difference * raw_difference # получим вектор 1х100
    scores[word] = -math.sqrt(sum(squared_difference)) # math.sqrt(sum(squared_difference)) - число
  return scores.most_common(10) # выводит 10 самых часто встречающихся


import collections

c = collections.Counter()

for word in ['spam', 'egg', 'spam', 'counter', 'counter', 'counter']:

     c[word] += 1


print(c)

Counter({'counter': 3, 'spam': 2, 'egg': 1})

In [ ]:
math.sqrt(sum(weights_0_1[5] * weights_0_1[5]))

0.37390070957014526

In [ ]:
for word,index in word2index.items():
  print(word)

In [ ]:
scores = Counter()
scores['influencing']

0

In [ ]:
Counter()[word]

0

In [ ]:
weights_0_1[:1]*weights_0_1[:1]

array([[2.75413908e-04, 1.94171530e-03, 9.99542553e-03, 1.56289647e-03,
        4.99125603e-03, 6.64751285e-03, 3.93730620e-03, 9.54059561e-04,
        4.26278175e-04, 6.02695535e-05, 2.61181060e-04, 1.37225053e-03,
        3.49393891e-03, 5.71891183e-03, 8.93449948e-03, 1.16236688e-03,
        2.73539828e-04, 1.37779839e-04, 5.17286216e-03, 3.64570844e-03,
        3.61789182e-03, 8.77075613e-03, 1.39242149e-03, 1.47951954e-03,
        5.66675176e-03, 6.22857676e-03, 6.88753226e-03, 8.49881971e-03,
        4.36047807e-03, 5.71967012e-03, 6.45301064e-03, 2.48960273e-04,
        8.38651287e-03, 4.39974451e-05, 1.47267307e-03, 1.36137930e-03,
        1.39130384e-03, 4.47897361e-03, 9.28184735e-03, 2.50288713e-03,
        9.55940657e-03, 2.46344768e-03, 1.92819362e-03, 3.34730119e-03,
        6.29718407e-03, 1.08603385e-04, 6.67801141e-03, 1.70380479e-03,
        1.80157228e-03, 5.47515430e-03]])

In [ ]:
weights_0_1[:1]

array([[-0.0165956 ,  0.0440649 , -0.09997713, -0.03953349, -0.07064882,
        -0.08153228, -0.06274796, -0.03088785, -0.02064651,  0.00776335,
        -0.0161611 ,  0.0370439 , -0.05910955,  0.07562349, -0.09452248,
         0.0340935 , -0.01653904,  0.01173797, -0.07192261, -0.0603797 ,
         0.06014891,  0.09365232, -0.03731516,  0.03846452,  0.07527783,
         0.07892133, -0.08299116, -0.09218904, -0.06603392,  0.0756285 ,
        -0.08033063, -0.01577847,  0.09157791,  0.00663306,  0.03837542,
        -0.03689687,  0.03730019,  0.06692513, -0.09634234,  0.05002886,
         0.09777222,  0.04963313, -0.0439112 ,  0.05785587, -0.0793548 ,
        -0.01042129,  0.0817191 , -0.04127717, -0.04244493, -0.07399429]])

In [ ]:
def sigmoid (x):
  return 1/(1 + np.ехр(-x))